// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $story_id_ from "./routes/story/[id].tsx";
import * as $story_id_viewbook from "./routes/story/[id]/viewbook.tsx";
import * as $Carousel from "./islands/Carousel.tsx";
import * as $InstallBanner from "./islands/InstallBanner.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/story/[id].tsx": $story_id_,
    "./routes/story/[id]/viewbook.tsx": $story_id_viewbook,
  },
  islands: {
    "./islands/Carousel.tsx": $Carousel,
    "./islands/InstallBanner.tsx": $InstallBanner,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
